WIREGUARD_IMAGE: "ghcr.io/jodevsa/wireguard-operator/wireguard:sha-9996ea23fac29e311682aedf3ef9426a7a5a5b78"
OPERATOR_IMAGE: "ghcr.io/jodevsa/wireguard-operator/operator:sha-9996ea23fac29e311682aedf3ef9426a7a5a5b78"