WIREGUARD_IMAGE: "ghcr.io/jodevsa/wireguard-operator/wireguard:sha-5aecfba4ede1c3383dd039aecb77b2abf577f0e3"
OPERATOR_IMAGE: "ghcr.io/jodevsa/wireguard-operator/operator:sha-5aecfba4ede1c3383dd039aecb77b2abf577f0e3"