WIREGUARD_IMAGE: "ghcr.io/jodevsa/wireguard-operator/wireguard:sha-51a4a542d128a3a389036d5dbd81ceee65c9ebca"
OPERATOR_IMAGE: "ghcr.io/jodevsa/wireguard-operator/operator:sha-51a4a542d128a3a389036d5dbd81ceee65c9ebca"