WIREGUARD_IMAGE: "ghcr.io/jodevsa/wireguard-operator/wireguard:sha-7b4133ef765b314d67b62455be3eea076deafa3d"
OPERATOR_IMAGE: "ghcr.io/jodevsa/wireguard-operator/operator:sha-7b4133ef765b314d67b62455be3eea076deafa3d"