WIREGUARD_IMAGE: "ghcr.io/jodevsa/wireguard-operator/wireguard:sha-ec94707713a3f0fc7c9a8c80aabfc3a4867baba8"
OPERATOR_IMAGE: "ghcr.io/jodevsa/wireguard-operator/operator:sha-ec94707713a3f0fc7c9a8c80aabfc3a4867baba8"