WIREGUARD_IMAGE: "ghcr.io/jodevsa/wireguard-operator/wireguard:sha-523f34501db88118ae817b27ee32d52b72d6beee"
OPERATOR_IMAGE: "ghcr.io/jodevsa/wireguard-operator/operator:sha-523f34501db88118ae817b27ee32d52b72d6beee"