name: Build Docker Images

on: [push, pull_request]
env:
  TARGET_PLATFORMS: linux/amd64,linux/arm64

jobs: 
  build-agent-docker:
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        image:
          - manager
          - agent
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
      name: Checkout repository
      with:
        submodules: true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate docker metadata
      id: image-meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository_owner }}/wireguard-operator/${{ matrix.image }}

    - uses: actions/setup-go@v3
      with:
        go-version: '^1.19'

    - name: Build and push docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: images/${{ matrix.image }}/Dockerfile
        platforms: ${{ matrix.platform }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.image-meta.outputs.tags }}
        labels: ${{ steps.image-meta.outputs.labels }}