name: build docker images
on:
  pull_request: {}

permissions:
  contents: read
  packages: write

jobs: 
  build-images:
    uses: ./.github/workflows/build-images.yaml
    with:
      push: false
      run_e2e: true
      platforms: "linux/amd64"
      ref: ${{ github.ref }}
