name: build docker images
on:
  pull_request: {}

permissions:
  contents: read
  packages: write

jobs: 
  build-images:
    uses: ./.github/workflows/build-images.yaml
    with:
      push: false
      upload_images: true
      platforms: "linux/amd64"
      ref: ${{ github.ref }}

  e2e:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: images
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/agent.tar
          docker load --input /tmp/manager.tar
          docker image ls -a


      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20'

      - name: run e2e
        run: |
          make run-e2e AGENT_IMAGE="agent:dev" MANAGER_IMAGE:"manager:dev"